# Generated by Django 5.2 on 2025-04-29 07:45

import django.core.validators
import patient.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('birth_date', models.DateField(validators=[patient.models.validate_birth_date], verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], max_length=1, verbose_name='Пол')),
                ('phone_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\+7\\d{10}$', message='Формат: +7XXXXXXXXXX')], verbose_name='Номер телефона')),
                ('filial', models.CharField(choices=[('0', ''), ('1', 'ГБ Троицкая амбулатория 1'), ('2', 'ГБ Троицкая амбулатория 2'), ('3', 'ГБ Троицкая амбулатория 3'), ('4', 'ГБ Троицкая амбулатория 4'), ('5', 'ГБ Троицкая (ПО)'), ('6', 'ГБ Троицкая (ДО)'), ('7', 'ГБ Троицкая филиал 1'), ('8', 'ГБ Троицкая филиал 2'), ('9', 'ГБ Троицкая филиал 3'), ('10', 'ГБ Троицкая филиал 4'), ('11', 'ГБ Троицкая филиал 5')], default='0', max_length=20, verbose_name='Филиал')),
                ('insurance_number', models.CharField(help_text='16 цифр без пробелов и разделителей', max_length=16, unique=True, validators=[patient.models.validate_insurance_number], verbose_name='Номер полиса ОМС')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['full_name'], name='patient_pat_full_na_14ae2a_idx'), models.Index(fields=['insurance_number'], name='patient_pat_insuran_06e4b2_idx')],
            },
        ),
    ]
