# Generated by Django 5.2 on 2025-04-30 06:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+7\\d{10}$', message='Формат: +7XXXXXXXXXX')], verbose_name='Номер телефона'),
        ),
    ]
