# Generated by Django 5.2 on 2025-05-06 12:23

import patient.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patient_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='insurance_number',
            field=models.CharField(db_index=True, help_text='16 цифр без пробелов и разделителей', max_length=16, unique=True, validators=[patient.models.validate_insurance_number], verbose_name='Номер полиса ОМС'),
        ),
    ]
