# Generated by Django 5.2 on 2025-05-20 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0003_alter_patient_insurance_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisabledChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mkb_code', models.CharField(max_length=10, verbose_name='Код МКБ')),
                ('status', models.CharField(choices=[('registered', 'Состоит'), ('new_current_mo', 'Впервые установлена в текущем МО'), ('new_other_mo', 'Прибыл с впервые установленной из другого МО'), ('existing_other_mo', 'Прибыл с ранее установленной из другого МО'), ('renewed', 'Возобновление прерванной инвалидности')], default='registered', max_length=20, verbose_name='Статус')),
                ('disability_date', models.DateField(blank=True, null=True, verbose_name='Дата установки инвалидности')),
                ('palliative', models.BooleanField(default=False, verbose_name='Паллиативный пациент')),
                ('removal_reason', models.CharField(blank=True, choices=[('moved', 'Выбыл на другое место жительства'), ('removed', 'Снятие инвалидности МСЭК'), ('died', 'Умер'), ('adult', 'Выбыл по достижению 18 лет'), ('refusal', 'Отказ от переосвидетельствования'), ('diagnosis_change', 'Изменение диагноза'), ('error', 'Ошибочная постановка')], max_length=20, null=True, verbose_name='Причина снятия')),
                ('removal_date', models.DateField(blank=True, null=True, verbose_name='Дата снятия')),
                ('comorbidities', models.TextField(blank=True, verbose_name='Сопутствующие диагнозы')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disabled_child', to='patient.patient')),
            ],
        ),
    ]
