# Generated by Django 5.2 on 2025-04-29 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icd_code', models.CharField(help_text='Международный код заболевания', max_length=5, verbose_name='Код МКБ-10')),
                ('disp_status', models.CharField(choices=[('состоит', 'Состоит'), ('с_впервые', 'С впервые'), ('с_ранее', 'С ранее')], help_text='Статус диспансерного наблюдения', max_length=10, verbose_name='Диспансерный учёт')),
                ('primary_reason', models.CharField(blank=True, choices=[('профосмотр', 'При профосмотре'), ('заболевание', 'По заболеванию')], max_length=12, null=True, verbose_name='Причина первичного выявления')),
                ('disp_start_date', models.DateField(help_text='Дата начала диспансерного наблюдения', verbose_name='Дата взятия на ДН')),
                ('disp_end_date', models.DateField(blank=True, null=True, verbose_name='Дата снятия с ДН')),
                ('remove_reason', models.CharField(blank=True, choices=[('не_явился', 'Не явился'), ('умер', 'Умер'), ('перешёл', 'Перешёл в другое МО'), ('выздоровел', 'Выздоровел')], max_length=12, null=True, verbose_name='Причина снятия')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='patient.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Диагноз',
                'verbose_name_plural': 'Диагнозы',
                'ordering': ['-disp_start_date'],
            },
        ),
    ]
