# Generated by Django 5.2 on 2025-04-29 12:17

import diagnos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='icd_code',
            field=models.CharField(help_text='Международный код заболевания', max_length=5, validators=[diagnos.models.validate_icd10_format], verbose_name='Код МКБ-10'),
        ),
    ]
