# Generated by Django 5.2 on 2025-04-30 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnos', '0002_alter_diagnosis_icd_code'),
        ('patient', '0002_alter_patient_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='age',
            field=models.PositiveSmallIntegerField(editable=False, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='filial',
            field=models.CharField(editable=False, max_length=20, null=True, verbose_name='Филиал прикрепления'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='full_name',
            field=models.CharField(editable=False, max_length=100, null=True, verbose_name='ФИО пациента'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='insurance_number',
            field=models.CharField(editable=False, max_length=16, null=True, verbose_name='Номер полиса'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='search_term',
            field=models.CharField(help_text='Введите полное ФИО пациента или номер полиса ОМС', max_length=100, null=True, verbose_name='Поиск пациента (ФИО или номер полиса)'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='patient',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='patient.patient', verbose_name='Пациент'),
        ),
        migrations.AlterUniqueTogether(
            name='diagnosis',
            unique_together={('patient', 'icd_code')},
        ),
    ]
