# Generated by Django 5.2 on 2025-04-30 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnos', '0003_diagnosis_age_diagnosis_filial_diagnosis_full_name_and_more'),
        ('patient', '0002_alter_patient_phone_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='diagnosis',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='patient.patient', verbose_name='Пациент'),
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='age',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='filial',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='insurance_number',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='search_term',
        ),
    ]
