# Generated by Django 5.2 on 2025-05-06 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnos', '0004_alter_diagnosis_unique_together_and_more'),
        ('patient', '0002_alter_patient_phone_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='diagnosis',
            unique_together={('patient', 'icd_code')},
        ),
    ]
