# Generated by Django 5.2 on 2025-05-06 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnos', '0005_alter_diagnosis_unique_together'),
        ('patient', '0002_alter_patient_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='patient',
            field=models.ForeignKey(help_text='Поиск по номеру полиса ОМС пациента', on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='patient.patient', verbose_name='Пациент'),
        ),
    ]
