# Generated by Django 5.2 on 2025-05-06 09:25

import death.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0002_alter_patient_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Death',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.CharField(help_text='Введите номер полиса ОМС для поиска пациента', max_length=16, verbose_name='Поиск по полису ОМС')),
                ('full_name', models.CharField(editable=False, max_length=100, verbose_name='ФИО пациента')),
                ('gender', models.CharField(editable=False, max_length=1, verbose_name='Пол')),
                ('birth_date', models.DateField(editable=False, verbose_name='Дата рождения')),
                ('age', models.PositiveSmallIntegerField(editable=False, verbose_name='Возраст')),
                ('filial', models.CharField(editable=False, max_length=20, verbose_name='Филиал прикрепления')),
                ('death_date', models.DateField(verbose_name='Дата смерти')),
                ('death_place', models.CharField(choices=[('дома', 'На дому'), ('стационар', 'В стационаре'), ('место_происшествия', 'На месте происшествия'), ('смп', 'В машине СМП'), ('другое', 'В другом месте')], max_length=20, verbose_name='Место смерти')),
                ('death_cause', models.CharField(max_length=5, validators=[death.models.validate_icd10_format], verbose_name='Причина смерти (МКБ-10)')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='death', to='patient.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Запись о смерти',
                'verbose_name_plural': 'Записи о смерти',
                'ordering': ['-death_date'],
            },
        ),
    ]
