# Generated by Django 5.2 on 2025-05-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('death', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='death',
            name='death_date',
            field=models.DateField(null=True, verbose_name='Дата смерти'),
        ),
    ]
